version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: keinos/sqlite3
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
    driver: local